/**
 * Generates a ready-to-run MCP server bundle from an agent definition.
 *
 * Returns a plain object mapping filename → string content, with no I/O or
 * Express dependencies so that every generator is unit-testable in isolation.
 *
 * @param {object} agent  - Serialized agent (output of serializeAgent)
 * @param {object} toolCatalog - TOOL_CATALOG from toolDefinitions.js
 * @returns {{ [filename: string]: string }}
 */
export function generateMcpBundle(agent, toolCatalog) {
  return {
    'server.js':   generateNodeServer(agent, toolCatalog),
    'server.py':   generatePythonServer(agent, toolCatalog),
    'package.json': generatePackageJson(agent),
    'server.json':  generateManifest(agent, toolCatalog),
    'Dockerfile':   generateDockerfile(),
    'README.md':    generateReadme(agent, toolCatalog),
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function slugify(name) {
  return (name || 'agent').replace(/[^a-z0-9]/gi, '-').toLowerCase();
}

function escapeJs(str) {
  return (str || '').replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

function escapePy(str) {
  return (str || '').replace(/\\/g, '\\\\').replace(/"""/g, '\\"\\"\\"');
}

// ---------------------------------------------------------------------------
// Node.js MCP server (uses @modelcontextprotocol/sdk)
// ---------------------------------------------------------------------------

function generateNodeServer(agent, toolCatalog) {
  const toolDefs = buildToolDefs(agent.tools || [], toolCatalog);

  const toolListEntries = toolDefs.map((t) => {
    const schemaStr = JSON.stringify(t.inputSchema, null, 4)
      .split('\n').join('\n    ');
    return `  {
    name: '${t.name}',
    description: '${t.description.replace(/'/g, "\\'")}',
    inputSchema: ${schemaStr},
  }`;
  }).join(',\n');

  const toolHandlers = toolDefs.map((t) => {
    const argNames = Object.keys(t.inputSchema.properties || {});
    const argList  = argNames.length ? `{ ${argNames.join(', ')} }` : '_args';
    return `    case '${t.name}': {
      // TODO: implement ${t.name}
      // ${t.description}
      return {
        content: [{ type: 'text', text: \`[${t.name}] received: ${argNames.map((a) => `${a}=\${${a}}`).join(', ') || '(no args)'}\` }],
      };
    }`;
  }).join('\n');

  return `#!/usr/bin/env node
/**
 * ${escapeJs(agent.name)} — MCP Server
 * Generated by AgentForge · https://agentforge.dev
 *
 * Persona: ${escapeJs(agent.persona)}
 *
 * Run with: node server.js
 * Or with Claude Desktop — see README.md for config.
 */
import { Server } from '@modelcontextprotocol/sdk/server/index.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from '@modelcontextprotocol/sdk/types.js';

// ---------------------------------------------------------------------------
// Agent configuration
// ---------------------------------------------------------------------------

const AGENT_NAME = \`${escapeJs(agent.name)}\`;
const SYSTEM_PROMPT = \`${escapeJs(agent.systemPrompt)}\`;

// ---------------------------------------------------------------------------
// Server setup
// ---------------------------------------------------------------------------

const server = new Server(
  { name: AGENT_NAME, version: '1.0.0' },
  { capabilities: { tools: {} } }
);

// List available tools
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
${toolListEntries}
  ],
}));

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
${toolHandlers}
    default:
      throw new Error(\`Unknown tool: \${name}\`);
  }
});

// ---------------------------------------------------------------------------
// Start server
// ---------------------------------------------------------------------------

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error(\`\${AGENT_NAME} MCP server running on stdio\`);
}

main().catch(console.error);
`;
}

// ---------------------------------------------------------------------------
// Python MCP server (uses mcp / FastMCP)
// ---------------------------------------------------------------------------

function generatePythonServer(agent, toolCatalog) {
  const toolDefs = buildToolDefs(agent.tools || [], toolCatalog);

  const toolFunctions = toolDefs.map((t) => {
    const props = t.inputSchema.properties || {};
    const required = new Set(t.inputSchema.required || []);
    const params = Object.entries(props).map(([k, v]) => {
      const pyType = jsonTypeToPy(v.type);
      return required.has(k) ? `${k}: ${pyType}` : `${k}: ${pyType} = None`;
    });
    const paramStr = params.length ? params.join(', ') : '';
    const argSummary = params.length
      ? params.map((p) => `${p.split(':')[0]}={${p.split(':')[0]}}`).join(', ')
      : '';

    return `
@mcp.tool()
async def ${t.name}(${paramStr}) -> str:
    """${escapePy(t.description)}"""
    # TODO: implement ${t.name}
    return f"[${t.name}] received: ${argSummary || '(no args)'}"
`;
  }).join('');

  return `#!/usr/bin/env python3
"""
${escapePy(agent.name)} — MCP Server (Python)
Generated by AgentForge · https://agentforge.dev

Persona: ${escapePy(agent.persona)}

Run with: python server.py
Requires: pip install mcp
"""

from mcp.server.fastmcp import FastMCP

# ---------------------------------------------------------------------------
# Agent configuration
# ---------------------------------------------------------------------------

AGENT_NAME = """${escapePy(agent.name)}"""
SYSTEM_PROMPT = """${escapePy(agent.systemPrompt)}"""

# ---------------------------------------------------------------------------
# Server setup
# ---------------------------------------------------------------------------

mcp = FastMCP(AGENT_NAME)

# ---------------------------------------------------------------------------
# Tool definitions
# ---------------------------------------------------------------------------
${toolFunctions}
# ---------------------------------------------------------------------------
# Start server
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    mcp.run()
`;
}

// ---------------------------------------------------------------------------
// package.json
// ---------------------------------------------------------------------------

function generatePackageJson(agent) {
  return JSON.stringify({
    name: slugify(agent.name),
    version: '1.0.0',
    type: 'module',
    description: `${agent.persona || agent.name} MCP Server — generated by AgentForge`,
    main: 'server.js',
    scripts: {
      start: 'node server.js',
    },
    dependencies: {
      '@modelcontextprotocol/sdk': '^1.0.0',
    },
    engines: {
      node: '>=18',
    },
  }, null, 2);
}

// ---------------------------------------------------------------------------
// server.json — MCP manifest
// ---------------------------------------------------------------------------

function generateManifest(agent, toolCatalog) {
  const toolDefs = buildToolDefs(agent.tools || [], toolCatalog);
  return JSON.stringify({
    name: agent.name,
    version: '1.0.0',
    description: agent.persona || agent.systemPrompt?.slice(0, 120) || '',
    systemPrompt: agent.systemPrompt || '',
    tools: toolDefs.map((t) => ({
      name: t.name,
      description: t.description,
      inputSchema: t.inputSchema,
    })),
    generatedBy: 'AgentForge',
    schemaVersion: 1,
  }, null, 2);
}

// ---------------------------------------------------------------------------
// Dockerfile
// ---------------------------------------------------------------------------

function generateDockerfile() {
  return `FROM node:20-slim
WORKDIR /app

COPY package.json .
RUN npm install --production --silent

COPY server.js .

# MCP servers communicate over stdio — no port needed.
CMD ["node", "server.js"]
`;
}

// ---------------------------------------------------------------------------
// README.md
// ---------------------------------------------------------------------------

function generateReadme(agent, toolCatalog) {
  const toolDefs = buildToolDefs(agent.tools || [], toolCatalog);
  const slug = slugify(agent.name);
  const toolList = toolDefs.map((t) => `- **${t.name}** — ${t.description}`).join('\n');
  const hasHttpTool = (agent.tools || []).includes('http_request');

  const claudeDesktopConfig = JSON.stringify({
    mcpServers: {
      [slug]: {
        command: 'node',
        args: [`/path/to/${slug}/server.js`],
      },
    },
  }, null, 2);

  const envSection = hasHttpTool ? `
## Environment Variables

| Variable | Description | Required |
|----------|-------------|----------|
| \`BASE_URL\` | Default base URL for HTTP requests | No |
| \`API_KEY\` | API key for authenticated requests | No |

Set them before starting the server:
\`\`\`bash
export API_KEY=your_key_here
node server.js
\`\`\`
` : '';

  return `# ${agent.name} — MCP Server

${agent.persona ? `> ${agent.persona}\n` : ''}
Generated by [AgentForge](https://agentforge.dev) · Export date: ${new Date().toISOString().slice(0, 10)}

## About this agent

${agent.systemPrompt || '_No system prompt defined._'}

## Included tools

${toolList}

## Prerequisites

- **Node.js 18+** (for \`server.js\`)
- **Python 3.10+** with \`pip install mcp\` (for \`server.py\`)
- **Docker** (optional, for containerised deployment)

---

## Node.js setup

\`\`\`bash
npm install
node server.js
\`\`\`
${envSection}
## Python setup

\`\`\`bash
pip install mcp
python server.py
\`\`\`

## Docker setup

\`\`\`bash
docker build -t ${slug} .
docker run --rm -i ${slug}
\`\`\`

## Use with Claude Desktop

Add to your \`claude_desktop_config.json\`:

\`\`\`json
${claudeDesktopConfig}
\`\`\`

Config file location:
- **macOS**: \`~/Library/Application Support/Claude/claude_desktop_config.json\`
- **Windows**: \`%APPDATA%\\Claude\\claude_desktop_config.json\`

Then restart Claude Desktop. The \`${slug}\` server will appear in the tools panel.

## Implementing the tools

Each tool in \`server.js\` (and \`server.py\`) contains a \`// TODO: implement\` stub.
Replace the stub with your real logic:

\`\`\`js
case 'my_tool': {
  const result = await callMyExternalService(args.input);
  return { content: [{ type: 'text', text: result }] };
}
\`\`\`

## Debugging

Run with verbose output:
\`\`\`bash
MCP_LOG=debug node server.js
\`\`\`

Use the [MCP Inspector](https://github.com/modelcontextprotocol/inspector) to test tools interactively:
\`\`\`bash
npx @modelcontextprotocol/inspector node server.js
\`\`\`

---
*Generated with AgentForge · [MCP specification](https://modelcontextprotocol.io)*
`;
}

// ---------------------------------------------------------------------------
// Shared tool-definition builder
// ---------------------------------------------------------------------------

const DEFAULT_INPUT_SCHEMA = {
  type: 'object',
  properties: { input: { type: 'string', description: 'Tool input' } },
  required: ['input'],
};

/**
 * Builds a normalized list of MCP tool definitions from agent tool IDs.
 * Handles both "server" tools (no client-side input_schema) and "client" tools.
 */
function buildToolDefs(toolIds, toolCatalog) {
  return toolIds.map((id) => {
    const entry = toolCatalog[id];
    if (!entry) {
      return {
        name: id,
        description: `Tool: ${id}`,
        inputSchema: DEFAULT_INPUT_SCHEMA,
      };
    }
    const at = entry.anthropicTool;
    return {
      name: at.name || id,
      description: at.description || entry.label || id,
      inputSchema: at.input_schema || DEFAULT_INPUT_SCHEMA,
    };
  });
}

// ---------------------------------------------------------------------------
// Python type helpers
// ---------------------------------------------------------------------------

function jsonTypeToPy(type) {
  switch (type) {
    case 'string':  return 'str';
    case 'number':
    case 'integer': return 'float';
    case 'boolean': return 'bool';
    case 'array':   return 'list';
    case 'object':  return 'dict';
    default:        return 'str';
  }
}
